services:
  - type: web
    name: backend-compra-pronta
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: BCRYPT_ROUNDS
        value: 12
      - key: PORT
        value: 10000
      - key: ALLOWED_ORIGINS
        value: https://your-frontend-domain.com
    healthCheckPath: /health